services:
  - type: web
    name: quiz-app
    env: node
    buildCommand: npm install && (cd client && npm install && npm run build)
    startCommand: node ./server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false 